---
- hosts: k8s-masters
  become: yes
  gather_facts: no
  tasks:

  - name: install kubelet
    apt:
      name: kubelet={{ k8s_version }}

  - name: install kubectl
    apt:
      name: kubectl={{ k8s_version }}

  - name: install kubeadm
    apt:
      name: kubeadm={{ k8s_version }}

  - name: check if kubeadm-config.yml exists
    stat:
      path: kubeadm-config.yml
    register: kubeadm_config
    tags:
    - test

  - name: generate kubeadm-config.yml
    shell: kubeadm config print init-defaults > kubeadm-config.yml
    when: kubeadm_config.stat.isreg is not defined
    tags:
    - test

  - name:  
